<?xml version="1.0"?>


<robot name="boxxo" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:include filename="$(find boxxo_core)/urdf/wheel.urdf.xacro"/>
	<xacro:include filename="$(find boxxo_core)/urdf/boxxo_arm.urdf.xacro"/>
    
    <!-- Chassis Properties -->
	<xacro:property name="chassis_length" value="1.6256"/>
	<xacro:property name="chassis_width" value="1.2446"/>
	<xacro:property name="chassis_height" value="0.25"/>
	<xacro:property name="chassis_mass" value="0"/>
	
	<!-- Wheel Properties -->
	<xacro:property name="wheel_depth" value="0.1286"/>
	<xacro:property name="wheel_radius" value="0.3032"/>
	<xacro:property name="wheel_mass" value="35"/>
	<xacro:property name="wheel_x_spacing" value="${chassis_length/2}"/>
	<xacro:property name="wheel_y_spacing" value="${chassis_width/2}"/>
	<xacro:property name="wheel_z_spacing" value="${chassis_height/4}"/>
	
	<!-- Arm Location -->
	<xacro:property name="boxxo_arm_x" value=".2064"/>
	<xacro:property name="boxxo_arm_y" value=".3"/>
	<xacro:property name="boxxo_arm_z" value=".4"/>
	
	<link name="base_link"/>
	
	<!-- The chassis of the rover -->
	<link name="chassie">
		<visual>
			<origin xyz="0 0 0.125" rpy="0 0 0"/>
			<geometry>
				<box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0.125" rpy="0 0 0"/>
			<geometry>
				<box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
			</geometry>
		</collision>
		
		<inertial>
			<origin xyz="0 0 0.125" rpy="0 0 0"/>
			<mass value="${chassis_mass}"/>
			<inertia ixx="1.25" ixy="0.0" ixz="0.0" iyy="7.0" iyz="0.0" izz="0.0" />
		</inertial>
	</link>
	<joint name="reality_glue" type="fixed">
		<parent link="base_link"/>
		<child link="chassie"/>
	</joint>
	
	
	<xacro:wheel prefix="front_left" parent="chassie" wheelrad="${wheel_radius}" wheeldepth="${wheel_depth}" wheelkg="${wheel_mass}">
		<origin xyz="${wheel_x_spacing} -${wheel_y_spacing + (wheel_depth/2)} ${wheel_z_spacing}" rpy="0 0 0"/>
		<inertia ixx="0.08" ixy="0.0" ixz="0.0" iyy="0.14" iyz="0.0" izz="0.08"/>
	</xacro:wheel>
	<xacro:wheel prefix="front_right" parent="chassie" wheelrad="${wheel_radius}" wheeldepth="${wheel_depth}" wheelkg="${wheel_mass}">
		<origin xyz="${wheel_x_spacing} ${wheel_y_spacing + (wheel_depth/2)} ${wheel_z_spacing}" rpy="0 0 0"/>
		<inertia ixx="0.08" ixy="0.0" ixz="0.0" iyy="0.14" iyz="0.0" izz="0.08"/>
	</xacro:wheel>
	<xacro:wheel prefix="rear_left" parent="chassie" wheelrad="${wheel_radius}" wheeldepth="${wheel_depth}" wheelkg="${wheel_mass}">
		<origin xyz="-${wheel_x_spacing} -${wheel_y_spacing + (wheel_depth/2)} ${wheel_z_spacing}" rpy="0 0 0"/>
		<inertia ixx="0.08" ixy="0.0" ixz="0.0" iyy="0.14" iyz="0.0" izz="0.08"/>
	</xacro:wheel>
	<xacro:wheel prefix="rear_right" parent="chassie" wheelrad="${wheel_radius}" wheeldepth="${wheel_depth}" wheelkg="${wheel_mass}">
		<origin xyz="-${wheel_x_spacing} ${wheel_y_spacing + (wheel_depth/2)} ${wheel_z_spacing}" rpy="0 0 0"/>
		<inertia ixx="0.08" ixy="0.0" ixz="0.0" iyy="0.14" iyz="0.0" izz="0.08"/>
	</xacro:wheel>
	
	
	<xacro:boxxo_arm endeffector="" prefix="left" parent="chassie">
		<origin xyz="${boxxo_arm_x} ${boxxo_arm_y} ${boxxo_arm_z}" rpy="0 0 0"/>
	</xacro:boxxo_arm>
	<xacro:boxxo_arm endeffector="" prefix="right" parent="chassie">
		<origin xyz="${boxxo_arm_x} -${boxxo_arm_y} ${boxxo_arm_z}" rpy="0 0 0"/>
	</xacro:boxxo_arm>
	
	
	
	
</robot>
